import { QTableColumn } from 'quasar';

export const accountColumns = [
  {
    headerStyle: 'font-size: 20px',
    name: 'name',
    field: (row: { name: string }) => row.name,
    label: 'Name',
    align: 'left',
    required: true,
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'email',
    field: 'email',
    label: 'Email',
    align: 'left',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'institution',
    field: 'instKey',
    label: 'Institution',
    align: 'center',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'role',
    field: 'role',
    label: 'Role',
    align: 'center',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'qredits',
    field: 'qredits',
    label: 'Total QRedits',
    align: 'right',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'usedQredits',
    field: 'usedQredits',
    label: 'Allocated',
    align: 'right',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'remainingQRedits',
    field: (row) => (row.qredits || 0) - (row.usedQredits || 0),
    label: 'Remaining',
    align: 'right',
    sortable: true,
  },
  {
    headerStyle: 'font-size: 20px',
    name: 'status',
    field: 'status',
    label: 'Status',
    align: 'center',
    sortable: true,
  },
] as QTableColumn[];
